baseURL: https://grip.energy/
languageCode: en-us
title: GRIP
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Grip Website
    description: "Grid Resilience & Intelligence Project"
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: false
    disableSpecial1stPost: true
    comments: false
    hidemeta: false
    showtoc:
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "http://drive.google.com/uc?export=view&id=1AAQQvjCWqY0XMdCdFCPPAAqrwNMw_-Jm"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "GRIP"
    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "GRIP"
        subtitle: "GRIP is a project led by the Department of Energy’s SLAC National Accelerator Laboratory that combines artificial intelligence with massive amounts of data and industry experience from a dozen U.S. partners to identify places where the electric grid is vulnerable to disruption, reinforce those spots in advance and recover faster when failures do occur."
        # imageUrl: "https://raw.githubusercontent.com/PresencePG/grip-client/a8e8ce832ae946ce698a1cb700e2d8d481a60f72/src/css/zeplin/DataManagement/img/sidebar.svg?token=AHAIV2ALO2EKQJNWKC52MFDAMIQ3C"
        imageWidth: 200
        imageHeight: 130
        imageTitle: my image

    # home-info mode
    homeInfoParams:
        Title: "GRIP"

        Content: "."

    socialIcons:
        - name: github
          url: "https://github.com/gripenergy"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Getting Started Guide
          name: Getting Started Guide
          url: /getting-started-guide/
          weight: 10
        - identifier: Use Cases
          name: Use Cases
          url: /use-cases/
          weight: 20
        - identifier: Publications
          name: Publications
          url: /publications/
          weight: 30
        - identifier: Pilots
          name: Pilots
          url: /pilots/
          weight: 40
        - identifier: Team
          name: Team
          url: /team/
          weight: 50
        - identifier: Contact
          name: Contact
          url: /contact/
          weight: 60
